### ISSUE TITLE
翻译check

### ISSUE THREAD

**Issue by AllenKaiChen** [gdut-yy/A-Philosophy-of-Software-Design-zh#14]
前言部分第二段“I have not been able to identify a single class in any university where problem decomposition is a central topic.”翻译成“我还无法在任何将问题分解作为中心主题的大学中确定一个班级。”感觉不妥，有些问题；翻译为“我还没有在任何一所大学里找到一门课程将问题分解作为中心主题。”可能·更恰当一点。

**Comment by gdut-yy** [comment]
I have not been able to identify a single class in any university where problem decomposition is a central topic.
> 在任何一所大学里，我都没能找到一个以问题分解为中心主题的班级。

**Comment by AllenKaiChen** [comment]
> I have not been able to identify a single class in any university where problem decomposition is a central topic.
> 
> > 在任何一所大学里，我都没能找到一个以问题分解为中心主题的班级。

@gdut-yy 
这里的class翻译成班级不是很好，class还有“ an occasion when a group of students meets to be taught ”，即课的意思，这里用“课程”这个意思是不是会更贴切一点？

**Comment by gdut-yy** [comment]
有道理 学习了

**Comment by gdut-yy** [comment]
@AllenKaiChen fixed by 69960fe9893da3cdb6840e98fc5c056034e05f62
