### ISSUE TITLE
能提供一份全英文或者全中文的吗？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [gdut-yy/A-Philosophy-of-Software-Design-zh#7]
感谢翻译使得我读到了这么精彩的书，但是中英文来回切换看感觉思维总是在断，只看中文每次要跳过一段英文，跳过这段时间，思维和上一段连接不上了有些，并不是理解上的困难，而是纸面的空间跳跃花费阅读和思考时间，所以能提供一份完整的中文版本的翻译吗，感谢~

**Comment by gdut-yy** [comment]
@xiaozhiliaoo 技术上可以通过 vuepress 的 i18n 方案实现，可参考官方文档 https://vuepress.vuejs.org/guide/i18n.html
即 http://gdut_yy.gitee.io/doc-aposd/zh/ 路径下为全中文，即 http://gdut_yy.gitee.io/doc-aposd/en/ 路径下为全英文。
中英混编的原因在于英文文档翻译成中文时候，容易因翻译质量让读者感到困惑，所以排版上放在一起。

短期方案 全英文版本，查看之前的提交即可（即 git checkout 137a8eb02e6a9d551c17f392712c51a33ad265c8）
关于全中文版本 有一定工作量。后续可以完善。

**Comment by xiaozhiliaoo** [comment]
好的，我把你们翻译的中文全部复制出来，打印出来看了。这本书后期会出版吗？感觉很精彩的一本书，

**Comment by xiaozhiliaoo** [comment]
国内关于软件设计书感觉很少，感觉集中在02-06年之间的ood，uml，tdd，Kent Beck，bob大叔的书之类的，像这本书的设计介绍国内比较少见，

**Comment by dannysunyu** [comment]
请问译者打算联系出版社吗？

**Comment by cch123** [comment]
@xiaozhiliaoo , clean architecture

**Comment by IronsDu** [comment]
@xiaozhiliaoo 有一本相对较早的书《程序设计实践》

**Comment by qiutian00** [comment]
好书， 辛苦了！
